-- Jalankan di Supabase SQL Editor
-- 1) Buat tabel untuk menyimpan metadata foto + geolokasi
create table if not exists public.photo (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  latitude float8 not null,
  longitude float8 not null,
  image_url text not null
);

-- 2) Aktifkan RLS
alter table public.photo enable row level security;

-- 3) Policy praktikum: izinkan semua operasi untuk anon/public
-- Catatan: ini untuk latihan dasar, bukan untuk production.
create policy "Allow all photo access"
on public.photo
for all
to anon
using (true)
with check (true);

-- 4) Buat bucket storage bernama photos
insert into storage.buckets (id, name, public)
values ('photos', 'photos', true)
on conflict (id) do update set public = true;

-- 5) Policy storage agar aplikasi bisa upload dan membaca file
create policy "Allow public photo upload"
on storage.objects
for insert
to anon
with check (bucket_id = 'photos');

create policy "Allow public photo read"
on storage.objects
for select
to anon
using (bucket_id = 'photos');
